# Propiedas del servidor
spring.application.name=DroneWarsServer
server.port=6969
server.address=0.0.0.0

# Propiedas de logs
logging.level.root=WARN
logging.level.udegames.dronewarsserver=DEBUG
logging.level.udegames.dronewarsserver.websocket=INFO
logging.level.udegames.dronewarsserver.service=INFO
logging.level.udegames.dronewarsserver.engine=DEBUG

# Fomato logs
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

spring.datasource.url=jdbc:postgresql://localhost:5432/dronewars
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Crear tablas al arrancar (BD debe existir)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/crearTablas.sql
spring.sql.init.continue-on-error=true