# Server properties
spring.application.name=DroneWarsServer
server.port=8081
server.address=0.0.0.0

# Logging properties
logging.level.root=WARN
logging.level.udegames.dronewarsserver=DEBUG
logging.level.udegames.dronewarsserver.websocket=INFO
logging.level.udegames.dronewarsserver.service=INFO
logging.level.udegames.dronewarsserver.engine=DEBUG

# Logging format
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n